version: '3'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ROCKET_ADDRESS: "0.0.0.0"
      DATABASE_URL: "${DATABASE_URL}"

    healthcheck:
      test: ["CMD-SHELL 'pg_isready -u $POSTGRES_USER -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 10s

    volumes:
      - db_data:/var/lib/postgresql/data

  rust:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: "on-failure"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "sleep 10 && ./blog"


volumes:
  db_data:
    driver: local
