version: '3'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

  rust:
    build: .
    ports:
      - "8000:8000"

volumes:
  db_data:
    driver: local
