version: '3.8'

services:
  nginx:
      image: nginx:stable-alpine
      volumes:
       - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf  # Mount custom nginx configuration
       - files:/var/www/html   # Add shared volume for Nginx
      ports:
        - "${PORT_PROD}:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - files:/var/www/html   # Add shared volume for PHP
    environment:
      - APP_ENV=prod

volumes:
  files:
