version: '3.8'

services:
  nginx:
      image: nginx:latest
      volumes:
        - ./.docker/nginx/grilli.com.conf:/etc/nginx/sites-available/grilli.com
        - /etc/nginx/sites-enabled/grilli.com
      environment:
        - APP_ENV=prod
      ports:
        - "80:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  
