# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.

version: "3.9"
services:
  server:
    build: server/.
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  client:
    build: client/.
    ports:
      - "${CLIENT_LOCAL_PORT}:${CLIENT_PORT}"
